{{- range $serviceIndex, $service := (concat (list $.Values.service) ($.Values.additionalServices | default dict))  }}
{{- range $portMapIndex, $portMapUnused := $service.ports }}
{{- if eq $portMapIndex 0 }}
apiVersion: v1
kind: Service
metadata:
  {{- if $service.name }}
  name: {{ $service.name | quote }}
  {{- else }}
  name: {{ $.Release.Name | quote }}
  {{- end }}
  labels:
    "app.kubernetes.io/name": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    {{- range $labelName, $labelValue := $service.labels }}
    {{ $labelName | quote }}: {{ $labelValue | quote }}
    {{- end }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- range $annotationName, $annotationValue := $service.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
spec:
  {{- if $service.clusterIP }}
  clusterIP: {{ $service.clusterIP }}
  {{- end }}
  externalIPs:
    {{- range $externalIPIndex, $externalIP := $service.externalIPs }}
    - {{ $externalIP }}
    {{- end }}
  {{- if $service.externalName }}
  externalName: {{ $service.externalName }}
  {{- end }}
  {{- if $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $service.externalTrafficPolicy }}
  {{- end }}
  {{- if $service.healthCheckNodePort }}
  healthCheckNodePort: {{ $service.healthCheckNodePort }}
  {{- end }}
  {{- if $service.ipFamily }}
  ipFamily: {{ $service.ipFamily }}
  {{- end }}
  {{- if $service.loadBalancerIP }}
  loadBalancerIP: {{ $service.loadBalancerIP }}
  {{- end }}
  {{- if $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml $service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  {{- if $service.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ $service.publishNotReadyAddresses }}
  {{- end }}
  {{- if $service.sessionAffinity }}
  sessionAffinity: {{ $service.sessionAffinity }}
  {{- end }}
  {{- if $service.sessionAffinityConfig }}
  sessionAffinityConfig:
{{ toYaml $service.sessionAffinityConfig | indent 4 }}
  {{- end }}
  {{- if $service.topologyKeys }}
  topologyKeys:
{{ toYaml $service.topologyKeys | indent 4 }}
  {{- end }}
  ports:
    {{- range $portMapIndex, $portMap := $service.ports }}
    {{- if $portMap.name }}
    - name: {{ $portMap.name }}
    {{- else }}
    - name: "port-{{ $portMapIndex }}"
    {{- end }}
      {{- if $portMap.nodePort }}
      nodePort: {{ $portMap.nodePort }}
      {{- end }}
      port: {{ $portMap.port }}
      {{- if $portMap.containerPort }}
      targetPort: {{ $portMap.containerPort }}
      {{- else }}
      targetPort: {{ $portMap.port }}
      {{- end }}
      protocol: {{ $portMap.protocol | default "TCP" | quote }}
    {{- end }}
  selector:
    "app.kubernetes.io/name": "devspace-app"
    "app.kubernetes.io/component": {{ $.Release.Name | quote }}
  type: {{ $service.type | default "ClusterIP" | quote }}
{{- end }}
{{- end }}
{{- end }}
